// <auto-generated />
using System;
using GraphQlTower.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQlTower.Api.Data.Migrations;

[DbContext(typeof(ServiceRegistryDbContext))]
partial class ServiceRegistryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

        modelBuilder.Entity("GraphQlTower.Shared.Models.ServiceHeader", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<Guid>("UpstreamServiceId").HasColumnType("TEXT");
            b.Property<string>("Value").IsRequired().HasMaxLength(4096).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("UpstreamServiceId");
            b.ToTable("ServiceHeaders");
        });

        modelBuilder.Entity("GraphQlTower.Shared.Models.UpstreamService", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<bool>("IsEnabled").HasColumnType("INTEGER");
            b.Property<DateTimeOffset>("LastChecked").HasColumnType("TEXT");
            b.Property<int>("LastStatus").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            b.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("UpstreamServices");
        });

        modelBuilder.Entity("GraphQlTower.Shared.Models.ServiceHeader", b =>
        {
            b.HasOne("GraphQlTower.Shared.Models.UpstreamService", null)
                .WithMany("Headers")
                .HasForeignKey("UpstreamServiceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("GraphQlTower.Shared.Models.UpstreamService", b =>
        {
            b.Navigation("Headers");
        });
#pragma warning restore 612, 618
    }
}
