apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphql-tower.fullname" . }}-config
  labels:
    {{- include "graphql-tower.labels" . | nindent 4 }}
data:
  {{- if .Values.initialServices }}
  TOWER_INITIAL_SERVICES: {{ .Values.initialServices | toJson | quote }}
  {{- end }}
